# https://starship.rs/config/

[cmd_duration]
min_time = 500

[kubernetes]
symbol = "â›µ "
#style = "dimmed green"
disabled = true

#[kubernetes.context_aliases]
#"dev.local.cluster.k8s" = "dev"

[custom]

[custom.tab]
command = "tab --starship"
when = "tab --starship"
style = "bold blue"
disabled = true

